import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');
const cardWidth = (width - 48) / 2; 

export const createStyles = (colors: any) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 12,
      paddingTop: 12,
      backgroundColor: colors.primary,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 3,
      elevation: 3,
    },
    headerTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: '#FFF',
      letterSpacing: 0.3,
    },
    headerButtons: {
      flexDirection: 'row',
      gap: 8,
    },
    themeButton: {
      paddingVertical: 6,
      paddingHorizontal: 12,
      borderRadius: 18,
      backgroundColor: 'rgba(255, 255, 255, 0.25)',
      borderWidth: 1.5,
      borderColor: 'rgba(255, 255, 255, 0.4)',
    },
    themeButtonText: {
      color: '#FFF',
      fontSize: 12,
      fontWeight: '600',
    },
    
    cartButton: {
      paddingVertical: 6,
      paddingHorizontal: 12,
      borderRadius: 18,
      backgroundColor: 'rgba(255, 255, 255, 0.25)',
      borderWidth: 1.5,
      borderColor: 'rgba(255, 255, 255, 0.4)',
      position: 'relative',
    },
    cartButtonText: {
      color: '#FFF',
      fontSize: 12,
      fontWeight: '600',
    },
    cartBadge: {
      position: 'absolute',
      top: -6,
      right: -6,
      backgroundColor: '#DC2626',
      borderRadius: 12,
      minWidth: 24,
      height: 24,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 2,
      borderColor: colors.primary,
    },
    cartBadgeText: {
      color: '#FFF',
      fontSize: 12,
      fontWeight: 'bold',
    },
    logoContainer: {
      alignItems: 'center',
      paddingVertical: 8,
      paddingHorizontal: 16,
      backgroundColor: colors.cardBackground,
      borderBottomWidth: 0,
      borderBottomColor: colors.border,
    },
    logoCircle: {
      width: '100%',
      height: 80,
      borderRadius: 12,
      backgroundColor: 'transparent',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 0,
      overflow: 'hidden',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.06,
      shadowRadius: 2,
      elevation: 2,
    },
    logoImage: {
      width: '100%',
      height: '100%',
      borderRadius: 12,
    },
    logoText: {
      fontSize: 18,
      fontWeight: '600',
      color: colors.text,
      textAlign: 'center',
      letterSpacing: 0.2,
      display: 'none',
    },
    logoSubtext: {
      fontSize: 12,
      color: colors.textSecondary,
      marginTop: 0,
      fontStyle: 'normal',
      display: 'none',
    },
    scrollContent: {
      padding: 16,
    },
    sectionTitle: {
      fontSize: 22,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 16,
      letterSpacing: 0.2,
    },
    productsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      paddingBottom: 20,
    },
    productCard: {
      width: cardWidth,
      backgroundColor: colors.cardBackground,
      borderRadius: 14,
      marginBottom: 16,
      overflow: 'hidden',
      borderWidth: 0,
      borderColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 4,
      elevation: 3,
    },
    productImageContainer: {
      width: '100%',
      height: cardWidth * 0.85,
      backgroundColor: colors.background,
      overflow: 'hidden',
    },
    productImage: {
      width: '100%',
      height: '100%',
    },
    placeholderImage: {
      width: '100%',
      height: '100%',
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: colors.border,
    },
    placeholderText: {
      color: colors.textSecondary,
      fontSize: 12,
    },
    productInfo: {
      padding: 12,
    },
    productName: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.text,
      marginBottom: 6,
      minHeight: 36,
    },
    productPrice: {
      fontSize: 18,
      fontWeight: '700',
      color: colors.primary,
      marginBottom: 10,
    },
    addButton: {
      backgroundColor: colors.primary,
      paddingVertical: 10,
      paddingHorizontal: 14,
      borderRadius: 10,
      alignItems: 'center',
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.2,
      shadowRadius: 3,
      elevation: 2,
    },
    addButtonAdded: {
      backgroundColor: colors.success,
    },
    addButtonText: {
      color: '#FFF',
      fontSize: 14,
      fontWeight: 'bold',
      letterSpacing: 0.3,
    },
  });