// src/screens/Cart/styles.ts

import { StyleSheet } from 'react-native';

export const createStyles = (colors: any) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 12,
      paddingTop: 12,
      backgroundColor: colors.primary,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 4,
    },
    headerTitle: {
      fontSize: 22,
      fontWeight: 'bold',
      color: '#FFF',
      letterSpacing: 0.5,
    },
    iconButton: {
      paddingVertical: 8,
      paddingHorizontal: 16,
      borderRadius: 20,
      backgroundColor: 'rgba(255, 255, 255, 0.2)',
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.3)',
    },
    iconText: {
      color: '#FFF',
      fontSize: 14,
      fontWeight: '600',
    },
    scrollContent: {
      flex: 1,
      padding: 16,
    },
    emptyContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: 60,
    },
    emptyIcon: {
      fontSize: 80,
      marginBottom: 16,
    },
    emptyIconContainer: {
  alignItems: 'center',
  justifyContent: 'center',
  marginBottom: 24,
},
emptyCartIcon: {
  fontSize: 80,
},
emptySubText: {
  fontSize: 14,
  color: colors.textSecondary,
  marginBottom: 24,
},
    emptyText: {
      fontSize: 18,
      color: colors.textSecondary,
      textAlign: 'center',
      marginBottom: 24,
    },
    emptyButton: {
      backgroundColor: colors.primary,
      paddingVertical: 14,
      paddingHorizontal: 32,
      borderRadius: 12,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
      elevation: 3,
    },
    emptyButtonText: {
      color: '#FFF',
      fontSize: 16,
      fontWeight: 'bold',
      letterSpacing: 0.3,
    },
    cartItem: {
      backgroundColor: colors.cardBackground,
      borderRadius: 16,
      padding: 16,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 6,
      elevation: 3,
    },
    itemContent: {
      flexDirection: 'row',
      alignItems: 'flex-start',
    },
    itemImageContainer: {
      width: 90,
      height: 90,
      borderRadius: 12,
      backgroundColor: colors.background,
      overflow: 'hidden',
      marginRight: 14,
      borderWidth: 1,
      borderColor: colors.border,
    },
    itemImage: {
      width: '100%',
      height: '100%',
    },
    itemEmoji: {
      fontSize: 40,
    },
    itemInfo: {
      flex: 1,
      paddingRight: 8,
    },
    itemName: {
      fontSize: 16,
      fontWeight: 'bold',
      color: colors.text,
      marginBottom: 6,
    },
    priceContainer: {
      marginBottom: 10,
    },
    originalPrice: {
      fontSize: 13,
      color: colors.textSecondary,
      marginBottom: 2,
    },
    itemPrice: {
      fontSize: 20,
      fontWeight: 'bold',
      color: colors.primary,
    },
    quantityContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    quantityButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 3,
      elevation: 2,
    },
    quantityButtonText: {
      color: '#FFF',
      fontSize: 18,
      fontWeight: 'bold',
    },
    quantityText: {
      fontSize: 18,
      fontWeight: 'bold',
      color: colors.text,
      minWidth: 30,
      textAlign: 'center',
    },
    deleteButton: {
      justifyContent: 'center',
      alignItems: 'center',
      paddingLeft: 8,
    },
    deleteIcon: {
      fontSize: 32,
      color: colors.textSecondary,
      fontWeight: '300',
    },
    footer: {
      backgroundColor: colors.cardBackground,
      padding: 20,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -2 },
      shadowOpacity: 0.1,
      shadowRadius: 6,
      elevation: 6,
    },
    totalContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 16,
    },
    totalLabel: {
      fontSize: 20,
      fontWeight: 'bold',
      color: colors.text,
      letterSpacing: 0.3,
    },
    totalAmount: {
      fontSize: 28,
      fontWeight: 'bold',
      color: colors.primary,
      letterSpacing: 0.3,
    },
    checkoutButton: {
      backgroundColor: colors.success,
      paddingVertical: 16,
      borderRadius: 12,
      alignItems: 'center',
      shadowColor: colors.success,
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.3,
      shadowRadius: 6,
      elevation: 4,
    },
    checkoutButtonText: {
      color: '#FFF',
      fontSize: 18,
      fontWeight: 'bold',
      letterSpacing: 0.5,
    },
  });